apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: tf-jx-communal-jackal
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    gke:
      projectNumber: "220934549721"
    kanikoFlags: --skip-unused-stages --snapshotMode=redo
    project: jenkinsx-326916
    provider: gke
    registry: gcr.io
    zone: us-central1-a
  environments:
  - key: dev
    owner: jragustin
    repository: jx3-demo-cluster
  - key: staging
  - key: production
  ingress:
    domain: 34.123.107.139.nip.io
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: true
  kuberhealthy: true
  pipelineUser:
    username: jragustin
  repository: nexus
  secretStorage: gsm
  storage:
  - name: logs
    url: gs://logs-tf-jx-communal-jackal-db575f598a09
  - name: reports
    url: gs://reports-tf-jx-communal-jackal-db575f598a09
  - name: repository
    url: gs://repository-tf-jx-communal-jackal-db575f598a09
  vault: {}
  webhook: lighthouse
